# Gunakan Node.js sebagai base image
FROM node:20

# Set direktori kerja dalam kontainer
WORKDIR /usr/src/app

# Salin file package.json dan package-lock.json untuk menginstal dependensi
COPY package*.json ./

# Install dependensi aplikasi
RUN npm install

# Salin seluruh kode aplikasi ke dalam kontainer
COPY . .

# Expose port yang akan digunakan (misalnya port 502 untuk komunikasi dengan ESP32)
EXPOSE 3000

# Jalankan aplikasi
CMD ["npm", "start"]
